library(clusterProfiler)
gene_enrich<-read.table("difgene.txt")
rownames(gene_enrich)=gene_enrich[,1]
gene_enrich=gene_enrich[,-1]
gene<-row.names(gene_enrich)
gene.id <- bitr(gene, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
egocc<-enrichGO(gene = gene.id$ENTREZID, OrgDb = 'org.Hs.eg.db', ont = "cc",  pvalueCutoff = 0.05,readable= TRUE)   
write.table(egocc, "GO.cc3.txt", sep="\t")
pdf("GO3.cc.pdf",height=8,width=8)
barplot(egocc, showCategory=10) 
dev.off()
pdf("GOdot3.cc.pdf",height=8,width=8)
dotplot(egocc)
dev.off()
egobp<-enrichGO(gene = gene.id$ENTREZID, OrgDb = 'org.Hs.eg.db', ont = "bp",  pvalueCutoff = 0.05,readable= TRUE)   
write.table(egobp, "GO3.bp.txt", sep="\t")
pdf("GO3.bp.pdf",height=8,width=8)
barplot(egobp, showCategory=10) 
dev.off()
pdf("GOdot3.bp.pdf",height=8,width=8)
dotplot(egobp)
dev.off()
egomf<-enrichGO(gene = gene.id$ENTREZID, OrgDb = 'org.Hs.eg.db', ont = "mf",  pvalueCutoff = 0.05,readable= TRUE)   
write.table(egobp, "GO3.bp.txt", sep="\t")
pdf("GO3.mf.pdf",height=8,width=8)
barplot(egomf, showCategory=10) 
dev.off()
pdf("GOdot3.mf.pdf",height=8,width=8)
dotplot(egomf)
dev.off()